/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserProfileRouteImport } from './routes/user-profile'
import { Route as ScreeningRouteImport } from './routes/screening'
import { Route as ProfileShowcaseRouteImport } from './routes/profile-showcase'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as CandidatesIndexRouteImport } from './routes/candidates.index'
import { Route as OnboardingRecruiterRouteImport } from './routes/onboarding.recruiter'
import { Route as OnboardingCandidateRouteImport } from './routes/onboarding.candidate'
import { Route as HrPortalRouteImport } from './routes/hr.portal'
import { Route as CandidatesIdRouteImport } from './routes/candidates.$id'
import { Route as HrJobsIndexRouteImport } from './routes/hr.jobs.index'
import { Route as HrJobsNewRouteImport } from './routes/hr.jobs.new'
import { Route as HrJobsJob_idResultsRouteImport } from './routes/hr.jobs.$job_id.results'

const UserProfileRoute = UserProfileRouteImport.update({
  id: '/user-profile',
  path: '/user-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreeningRoute = ScreeningRouteImport.update({
  id: '/screening',
  path: '/screening',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileShowcaseRoute = ProfileShowcaseRouteImport.update({
  id: '/profile-showcase',
  path: '/profile-showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const CandidatesIndexRoute = CandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRecruiterRoute = OnboardingRecruiterRouteImport.update({
  id: '/recruiter',
  path: '/recruiter',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingCandidateRoute = OnboardingCandidateRouteImport.update({
  id: '/candidate',
  path: '/candidate',
  getParentRoute: () => OnboardingRoute,
} as any)
const HrPortalRoute = HrPortalRouteImport.update({
  id: '/hr/portal',
  path: '/hr/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIdRoute = CandidatesIdRouteImport.update({
  id: '/candidates/$id',
  path: '/candidates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HrJobsIndexRoute = HrJobsIndexRouteImport.update({
  id: '/hr/jobs/',
  path: '/hr/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const HrJobsNewRoute = HrJobsNewRouteImport.update({
  id: '/hr/jobs/new',
  path: '/hr/jobs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HrJobsJob_idResultsRoute = HrJobsJob_idResultsRouteImport.update({
  id: '/hr/jobs/$job_id/results',
  path: '/hr/jobs/$job_id/results',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/profile': typeof ProfileRoute
  '/profile-showcase': typeof ProfileShowcaseRoute
  '/screening': typeof ScreeningRoute
  '/user-profile': typeof UserProfileRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/hr/portal': typeof HrPortalRoute
  '/onboarding/candidate': typeof OnboardingCandidateRoute
  '/onboarding/recruiter': typeof OnboardingRecruiterRoute
  '/candidates/': typeof CandidatesIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/hr/jobs/new': typeof HrJobsNewRoute
  '/hr/jobs/': typeof HrJobsIndexRoute
  '/hr/jobs/$job_id/results': typeof HrJobsJob_idResultsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/profile-showcase': typeof ProfileShowcaseRoute
  '/screening': typeof ScreeningRoute
  '/user-profile': typeof UserProfileRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/hr/portal': typeof HrPortalRoute
  '/onboarding/candidate': typeof OnboardingCandidateRoute
  '/onboarding/recruiter': typeof OnboardingRecruiterRoute
  '/candidates': typeof CandidatesIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/hr/jobs/new': typeof HrJobsNewRoute
  '/hr/jobs': typeof HrJobsIndexRoute
  '/hr/jobs/$job_id/results': typeof HrJobsJob_idResultsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/profile': typeof ProfileRoute
  '/profile-showcase': typeof ProfileShowcaseRoute
  '/screening': typeof ScreeningRoute
  '/user-profile': typeof UserProfileRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/hr/portal': typeof HrPortalRoute
  '/onboarding/candidate': typeof OnboardingCandidateRoute
  '/onboarding/recruiter': typeof OnboardingRecruiterRoute
  '/candidates/': typeof CandidatesIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/hr/jobs/new': typeof HrJobsNewRoute
  '/hr/jobs/': typeof HrJobsIndexRoute
  '/hr/jobs/$job_id/results': typeof HrJobsJob_idResultsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/profile-showcase'
    | '/screening'
    | '/user-profile'
    | '/candidates/$id'
    | '/hr/portal'
    | '/onboarding/candidate'
    | '/onboarding/recruiter'
    | '/candidates/'
    | '/onboarding/'
    | '/hr/jobs/new'
    | '/hr/jobs/'
    | '/hr/jobs/$job_id/results'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/login'
    | '/profile'
    | '/profile-showcase'
    | '/screening'
    | '/user-profile'
    | '/candidates/$id'
    | '/hr/portal'
    | '/onboarding/candidate'
    | '/onboarding/recruiter'
    | '/candidates'
    | '/onboarding'
    | '/hr/jobs/new'
    | '/hr/jobs'
    | '/hr/jobs/$job_id/results'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/profile-showcase'
    | '/screening'
    | '/user-profile'
    | '/candidates/$id'
    | '/hr/portal'
    | '/onboarding/candidate'
    | '/onboarding/recruiter'
    | '/candidates/'
    | '/onboarding/'
    | '/hr/jobs/new'
    | '/hr/jobs/'
    | '/hr/jobs/$job_id/results'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  ProfileShowcaseRoute: typeof ProfileShowcaseRoute
  ScreeningRoute: typeof ScreeningRoute
  UserProfileRoute: typeof UserProfileRoute
  CandidatesIdRoute: typeof CandidatesIdRoute
  HrPortalRoute: typeof HrPortalRoute
  CandidatesIndexRoute: typeof CandidatesIndexRoute
  HrJobsNewRoute: typeof HrJobsNewRoute
  HrJobsIndexRoute: typeof HrJobsIndexRoute
  HrJobsJob_idResultsRoute: typeof HrJobsJob_idResultsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-profile': {
      id: '/user-profile'
      path: '/user-profile'
      fullPath: '/user-profile'
      preLoaderRoute: typeof UserProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screening': {
      id: '/screening'
      path: '/screening'
      fullPath: '/screening'
      preLoaderRoute: typeof ScreeningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile-showcase': {
      id: '/profile-showcase'
      path: '/profile-showcase'
      fullPath: '/profile-showcase'
      preLoaderRoute: typeof ProfileShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/candidates/': {
      id: '/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof CandidatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/recruiter': {
      id: '/onboarding/recruiter'
      path: '/recruiter'
      fullPath: '/onboarding/recruiter'
      preLoaderRoute: typeof OnboardingRecruiterRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/candidate': {
      id: '/onboarding/candidate'
      path: '/candidate'
      fullPath: '/onboarding/candidate'
      preLoaderRoute: typeof OnboardingCandidateRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/hr/portal': {
      id: '/hr/portal'
      path: '/hr/portal'
      fullPath: '/hr/portal'
      preLoaderRoute: typeof HrPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/$id': {
      id: '/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof CandidatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/jobs/': {
      id: '/hr/jobs/'
      path: '/hr/jobs'
      fullPath: '/hr/jobs/'
      preLoaderRoute: typeof HrJobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/jobs/new': {
      id: '/hr/jobs/new'
      path: '/hr/jobs/new'
      fullPath: '/hr/jobs/new'
      preLoaderRoute: typeof HrJobsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hr/jobs/$job_id/results': {
      id: '/hr/jobs/$job_id/results'
      path: '/hr/jobs/$job_id/results'
      fullPath: '/hr/jobs/$job_id/results'
      preLoaderRoute: typeof HrJobsJob_idResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OnboardingRouteChildren {
  OnboardingCandidateRoute: typeof OnboardingCandidateRoute
  OnboardingRecruiterRoute: typeof OnboardingRecruiterRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingCandidateRoute: OnboardingCandidateRoute,
  OnboardingRecruiterRoute: OnboardingRecruiterRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  ProfileRoute: ProfileRoute,
  ProfileShowcaseRoute: ProfileShowcaseRoute,
  ScreeningRoute: ScreeningRoute,
  UserProfileRoute: UserProfileRoute,
  CandidatesIdRoute: CandidatesIdRoute,
  HrPortalRoute: HrPortalRoute,
  CandidatesIndexRoute: CandidatesIndexRoute,
  HrJobsNewRoute: HrJobsNewRoute,
  HrJobsIndexRoute: HrJobsIndexRoute,
  HrJobsJob_idResultsRoute: HrJobsJob_idResultsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
